### ISSUE TITLE
Auto type detection is often wrong

### ISSUE THREAD

**Issue by NicHaley** [pubkey/broadcast-channel#88] opened 2020-01-09 02:05 UTC
According to the docs: "Depending in which environment this is used, a proper method is automatically selected to ensure it always works."

However, when using `broadcast-channel` in Safari with no options object, it will use "idb" by default. This gives the error "SecurityError: IDBFactory.open() called in an invalid security context". 

As far as I know Safari should use "localstorage".

Additionally, Internet Explorer has some odd behaviour. If the object 
```
{
    webWorkerSupport: false
}
```
is passed, it will also break (not sure which type). It works if I pass "idb" however.

**Comment by pubkey** [comment] 2020-01-09 06:36
Does the advanced test page work for you? https://pubkey.github.io/broadcast-channel/e2e.html

**Comment by NicHaley** [comment] 2020-01-09 15:25
The advanced page works for me, but in my project it does not.

I get the error:

> IDBFactory.open() called in an invalid security context

After doing some research it looks like Safari might not like using IndexedDB from an iFrame (ref: https://github.com/dfahlander/Dexie.js/issues/565).

If I explicitly set the type to "localStorage", everything works fine. For browsers that only support IndexedDB and LocalStorage like Safari, would it not be better to default to LocalStorage?

**Comment by pubkey** [comment] 2020-01-09 19:32
Does your iframe has a different origin than the parent?
I think this is a duplicate of https://github.com/pubkey/broadcast-channel/issues/36
Localstorage does not work in webworkers. I think the iframe is the edge-case here and we should not sacrifice default webworker support.

**Comment by NicHaley** [comment] 2020-01-09 20:06
Ah yes seems to be the same issue! I wasn't aware of the webworker tradeoff, makes sense. As suggested in #36 I think a helpful warning would go a long way since I thought this use-case would be supported.

Luckily the "type" options provides the scape hatch I need to get everything working anyways 👌

**Closed** 2020-01-09 20:13 UTC
