### ISSUE TITLE
Another periodic errors on iOS

### ISSUE THREAD

**Issue by dartess** [pubkey/broadcast-channel#28] opened 2019-09-16 15:44 UTC
Hello!

I'm sorry, but again I get errors on iOS that I can’t reproduce. This time like this:

```
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
```

in https://github.com/pubkey/broadcast-channel/blob/master/src/methods/indexed-db.js#L72

OS:
41.75% | iOS 12.3.1
22.90% | iOS 11.4.1
17.17% | iOS 12.4
11.78% | iOS 12.2
5.39% | iOS 12.1.3
1.01% | iOS 12.4.1

**Comment by pubkey** [comment] 2019-09-16 16:05
I am not sure if there is anything this module can do about it. When you send a message to another channel and the database is closing, the correct behavior is to throw an error.

**Closed** 2019-09-17 21:20 UTC

**Comment by Poky85** [comment] 2019-10-15 17:28
@pubkey Understand why those errors happens. But in fact these are unhandled errors. You should at least catch them so application that consumes `broadcast-channel` library doesn't end up with error reporting polluted with this.

In our app we frequently get those errors logged in Sentry.
- `Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`
(caused by `db.transaction` call in your [getMessagesHigherThen](https://github.com/pubkey/broadcast-channel/blob/master/src/methods/indexed-db.js#L101) method)
- `Failed to execute 'createObjectStore' on 'IDBDatabase': The database is not running a version change transaction.`
(caused by your [createDatabase](https://github.com/pubkey/broadcast-channel/blob/master/src/methods/indexed-db.js#L45) method)

I cannot catch this in my app, correct me if I am wrong.

**Comment by maxhallinan** [comment] 2020-07-22 16:46
@pubkey I agree with @Poky85 , asynchronous exceptions should be given Node-style error callbacks. The `Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.` in `getMessagesHigherThen` can't be caught/handled in a sane way because it occurs in an asynchronous loop. I am unable to reproduce it at the moment but it's likely this exception crashes the entire app, and there's no way to prevent this except by eliminating IndexedDB as a method.

**Comment by pubkey** [comment] 2020-07-22 17:45
@maxhallinan yes I also agree, we should gibe the user a way to catch this error. PR is welcomed.
