### ISSUE TITLE
'require is not defined' when used in Lit Web Component project

### ISSUE THREAD

**Issue by chandruchiku** [pubkey/broadcast-channel#697] opened 2021-07-29 10:32 UTC
## Case
BUG

## Issue
When I try to use the library in a Lit Element web component, it throws error 'require is not defined' 

## Info
Environment: Browser
Method: BroadcastChannel
Stack - Lit Web Component Typescript project scaffolded using OpenWC Generator

## Code

```js
  import { BroadcastChannel } from 'broadcast-channel';
  const channel = new BroadcastChannel('foobar');
  channel.postMessage('I am not alone');
```

## How to reproduce
 Scaffold a new WC project with 
` npm init @open-wc`

Then install the package, 
`npm install --save broadcast-channel`

Use the code to open a channel and post message anywhere in the project.

Run the webcomponent project with 'npm start'

**Comment by benmccann** [comment] 2021-08-01 06:18
This sounds like a duplicate of https://github.com/pubkey/broadcast-channel/issues/690

**Comment by pubkey** [comment] 2021-08-02 01:47
Please check again with the latest release. @chandruchiku

**Closed** 2021-08-03 15:27 UTC
