### ISSUE TITLE
Memory keep rising in Safari

### ISSUE THREAD

**Issue by zjsxdyw** [pubkey/broadcast-channel#103] opened 2020-02-18 03:39 UTC
https://github.com/pubkey/broadcast-channel/blob/ee06c529c18eaa5963d93b12960bcc16ddce40ed/dist/es/methods/indexed-db.js#L180

This function seems to create an infinite chain of Promise that causes Safari memory to keep rising.

**Comment by pubkey** [comment] 2020-02-18 08:52
Looks valid but I could not reproduce with chrome. Can you paste a screenshot of your safari profile?

**Comment by zjsxdyw** [comment] 2020-02-18 11:35
![image](https://user-images.githubusercontent.com/17042948/74732312-ecc95680-5284-11ea-9522-703a5b6bbf93.png)
Safari produces a lot of Promise and won't be recycled, and I think delete the return value of the function will resolve this problem.

**Comment by pubkey** [comment] 2020-02-18 12:43
Yes this sounds like a valid fix.
Can you try this locally and if it works make a PR?

**Comment by zjsxdyw** [comment] 2020-02-18 12:58
Okay, I have a try.

**Comment by pubkey** [comment] 2020-02-26 18:49
Merged, thank you.

**Closed by pubkey** 2020-02-26 18:49 UTC
