### ISSUE TITLE
Jest reports TypeError: broadcast_channel_1.default is not a constructor

### ISSUE THREAD

**Issue by saucesome** [pubkey/broadcast-channel#33] opened 2019-10-02 08:40 UTC
I'm importing broadcast-channel and everything is working great (thanks!). However, when writing tests, Jest is throwing an error:

`TypeError: broadcast_channel_1.default is not a constructor`

Any tips?

I'm importing BroadcastChannel like so:

`import BroadcastChannel from 'broadcast-channel';`

**Comment by pubkey** [comment] 2019-10-10 21:34
Duplicate of #9

**Closed by pubkey** 2019-10-10 21:34 UTC
